version: 2

sources:
  - name: raw
    database: ECOMMERCE_DB
    schema: RAW
    tables:
      - name: CUSTOMERS
      - name: GEOLOCATION
      - name: ORDER_ITEMS
      - name: ORDER_PAYMENTS
      - name: ORDER_REVIEWS
      - name: ORDERS
      - name: PRODUCTS
      - name: SELLERS
      - name: PRODUCT_CATEGORY_NAME_TRANSLATION